// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyX2IfeWXN62Izh3WRsyhmrC0Ojk-KjRo',
    appId: '1:106489263764:android:d276d790ea8ae4a64ea681',
    messagingSenderId: '106489263764',
    projectId: 'alive-22451',
    storageBucket: 'alive-22451.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLH0TyId1W5Hb0ZeF4UR6aCx-nkwwf8kw',
    appId: '1:106489263764:ios:d95d86a0873b3a8c4ea681',
    messagingSenderId: '106489263764',
    projectId: 'alive-22451',
    storageBucket: 'alive-22451.firebasestorage.app',
    androidClientId: '106489263764-7svc0tgq9s0l9uhgliavkfu9na7q24ai.apps.googleusercontent.com',
    iosClientId: '106489263764-058c0p22trrlokris3609lu3bgg683lm.apps.googleusercontent.com',
    iosBundleId: 'com.lvs.alive',
  );
}
